# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-29 01:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurants',
            name='waiting_time',
        ),
    ]
