# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-05 18:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_restaurants_waiting_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='rtemptime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Temp_wait_time', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
