# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-09 22:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20180405_1150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rtemptime',
            name='temp_date',
        ),
        migrations.AddField(
            model_name='rtemptime',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='rtemptime',
            name='Temp_wait_time',
            field=models.CharField(default='Not Entered', max_length=3),
        ),
    ]
